### ISSUE TITLE
Recent emotes

### ISSUE THREAD

**Issue by ApolloFiveM** [BombayV/anims#12]
It would be nice to see that when you use the emotes it sets it to you in an area where there are recent emotes and after 4 emotes, the last is removed and make space for the new emote

**Comment by BombayV** [comment]
I will be adding a command which will work this way.

/laste 1-5
If you have not played an anim, it will tell you.

**Comment by ApolloFiveM** [comment]
It's not possible to put into the ui? Like the favorite section

**Comment by BombayV** [comment]
Yeah, but only for 5 animations I don't think it would be worth the effort. I can do the command if that's something you're interested in.
