### ISSUE TITLE
Prop

### ISSUE THREAD

**Issue by Branqueador** [BombayV/anims#17]
It would be realy nice to be able to spawn a prop for example bumper or engine etc

**Comment by BombayV** [comment]
It already spawns with your animation. Or do you mean like create an actual prop?

**Comment by Branqueador** [comment]
Create a place where I can spawn the actual prop

**Comment by BombayV** [comment]
I like your idea, but I just don't know if this resource is the right one for this for the following factors.
1) How would prop creation be handled. How should a person decide where to place the specified object?
2) I feel like there would be a high restriction with the number and type of props you can place since it would be restricted to the ones in the `anims.json` or another `.json` file if I create one.

I feel like it would be better to create an entire new resource which handles prop spawning with coords positioning and everything.

**Comment by Branqueador** [comment]
For example if you do /e bumper or /e engine it spawns an object in your hands that would be nice 
But it would be nice for later a proper prop spawner

**Comment by BombayV** [comment]
> you do /e bumper or /e engine it spawns an object in your hands that would be nice

You can already do that by creating one yourself. You just have to find the right prop coords.
https://github.com/BombayV/anims/blob/main/anims.json#L359
^^ Example.

**Comment by Branqueador** [comment]
could i ask you how do you create a new column for example just for the props like the ones on the image? 
![image](https://user-images.githubusercontent.com/37988563/147773250-ef2c066e-553c-4df5-a767-f118dbfce450.png)

**Comment by BombayV** [comment]
https://github.com/BombayV/anims/blob/main/html/ui.html#L20

https://github.com/BombayV/anims/blob/main/html/css/style.css#L311

https://github.com/BombayV/anims/blob/main/html/js/listeners.js#L32

And when creating a new anim it needs to have the type you specified.

**Comment by Branqueador** [comment]
![image](https://user-images.githubusercontent.com/37988563/147774705-38fe6494-eb0c-4ec8-abab-875073acc527.png)
do you want me to do a pr when finished ?

**Comment by BombayV** [comment]
What do you want to implement?

**Comment by BombayV** [comment]
@Branqueador If you still have this in mind you can try making a PR.

**Comment by Branqueador** [comment]
What I’ve done is a new space and you can direct anims with props there so for example in the dpemotes if you do /e bumper it spawns a bumper in your hand hands that’s what I did .
Will do the pr today or tomorrow’s, still need to do a lot of animations but will do in the mean time

**Comment by Branqueador** [comment]
@BombayV  hey do i'm a noob with github but i'll leave a link of the fork i did with all changes please have a look and let me know if i can explain something
https://github.com/Branqueador/anims

**Comment by BombayV** [comment]
I opened a pull request for you.
#28

**Comment by BombayV** [comment]
Closing this since pr was created
