### ISSUE TITLE
Suggestion: Persistent Walk Styles

### ISSUE THREAD

**Issue by kunaiknife452** [BombayV/anims#2]
Not sure how feasible it is, but something such as this: https://github.com/ASSYNU/fivem-walking-styles where walks are saved in long-term memory would be a really useful feature.
Bonus points for framework support for QB-Core and ESX so that it can be set per-character instead of per-player.

**Comment by BombayV** [comment]
Thank you for the recommendation. I'll try doing it for the next update. ❤️

**Comment by BombayV** [comment]
Done. It should be pushed in next update.
