### ISSUE TITLE
Remove Blur effect

### ISSUE THREAD

**Issue by zf-development** [BombayV/anims#20]
For some of my players, the blur is making them lag a little in the menu. I would like to have a possibility to remove the blur / an explanation to remove it in the README.md it would be appreciated.

**Comment by BombayV** [comment]
I don't see how the blur effect can make people lag.
https://github.com/BombayV/anims/blob/main/client/nui.lua#L76
https://github.com/BombayV/anims/blob/main/client/nui.lua#L133
Those are the lines.

**Comment by Gameadictive** [comment]
Lanes changes so what are now?

**Comment by Gameadictive** [comment]
> I don't see how the blur effect can make people lag. https://github.com/BombayV/anims/blob/main/client/nui.lua#L76 https://github.com/BombayV/anims/blob/main/client/nui.lua#L133 Those are the lines.

Up
