### ISSUE TITLE
Easier Looping/Unlocked Movement

### ISSUE THREAD

**Issue by kunaiknife452** [BombayV/anims#26]
Would like to suggest a few super-useful features: 

- Ability to set default looping/movement settings for each animation in the anims.json
- Ability to choose looping/movement settings for each animation when played with the PlayEmote export from another script.

**Comment by BombayV** [comment]
This exists. I just have not had time to test it.
https://github.com/BombayV/anims/pull/19

> Ability to choose looping/movement settings for each animation when played with the PlayEmote export from another script.

I don't think I can do this since it fetches the data from the anim block class. Unless I change the way it works, I won't be adding this.

**Comment by BombayV** [comment]
It has been merged #32
