### ISSUE TITLE
Help TriggerEvent

### ISSUE THREAD

**Issue by MercedessBenz** [BombayV/anims#30]
I have problem with `TriggerEvent('animations:client:EmoteCommandStart', {"eat"})`
It has no animation
How to fix this

**Comment by BombayV** [comment]
That's dpemotes stuff. Use the following.

https://github.com/BombayV/anims/issues/4#issuecomment-998472663

**Comment by MercedessBenz** [comment]
@BombayV 
Is there a command to cancel the animation?

For old dpemotes will use this
`TriggerEvent('animations:client:EmoteCommandStart', {"c"})`

What I have to do?

**Comment by BombayV** [comment]
You can do the following if it works.

`exports['anims']:Load.Cancel()`

**Comment by MercedessBenz** [comment]
@BombayV 
It doesn't work, the system gives an error

**Comment by BombayV** [comment]
Show me the error.

**Comment by BombayV** [comment]
It might be due to something like this.
Try this,
```lua
local Load = exports['anims']:Load()

Load.Cancel()
```

**Comment by MercedessBenz** [comment]
![image](https://user-images.githubusercontent.com/25920716/149059339-cb5b8e32-74d5-4216-ab79-267fcb3f0c54.png)

**Comment by BombayV** [comment]
Mmm

**Comment by BombayV** [comment]
Try to remove the `()` from load.

**Comment by MercedessBenz** [comment]
![image](https://user-images.githubusercontent.com/25920716/149062480-31d3c3b6-3604-4e5a-ba9f-4c02179fa3ef.png)
It's the same error as the first one

**Comment by BombayV** [comment]
That's not an error with the anims. Show what you have.

**Comment by MercedessBenz** [comment]
![image](https://user-images.githubusercontent.com/25920716/149066891-44974872-1d84-4f01-b46f-0f91418cced1.png)

**Comment by BombayV** [comment]
`local Load = exports['anims']:Load`

**Comment by MercedessBenz** [comment]
> ![image](https://user-images.githubusercontent.com/25920716/149059339-cb5b8e32-74d5-4216-ab79-267fcb3f0c54.png)

**It will have error like this**

**Comment by MercedessBenz** [comment]
![image](https://user-images.githubusercontent.com/25920716/149070108-dae423dc-79c2-4558-8438-dac9d70afea6.png)

**Comment by BombayV** [comment]
I'll test today when I come back from school.

**Comment by BombayV** [comment]
You can test again. Put this at the top of the resource.
```lua
local Load = exports['anims']:Load()
```
Then you can do the following wherever you want.
```lua
Load.Cancel()
```

**Comment by MercedessBenz** [comment]
![image](https://user-images.githubusercontent.com/25920716/149289619-afda8a7c-1e39-4578-b8c0-b6e99ec77021.png)

**Comment by BombayV** [comment]
That's really weird. I guess I need to test again. Just to make sure, the anims  are starting before the resource right?

**Comment by MercedessBenz** [comment]
I ensure anims only after core

**Comment by BombayV** [comment]
@MercedessBenz I appear to have no issues.
![image](https://user-images.githubusercontent.com/72895600/149601308-5a9627a5-2b36-4524-a5f7-229bb84db4df.png)

I just made sure the anims start before whatever resource I need.

**Comment by MercedessBenz** [comment]
I think I figured out where the problem lies
Maybe I haven't updated your script yet

Before
![image](https://user-images.githubusercontent.com/25920716/149606434-7104d45b-de8e-488e-bf75-c12dc1b12c94.png)

After
![image](https://user-images.githubusercontent.com/25920716/149606451-afaa5d21-606d-4d77-a64f-82f49c48b9cc.png)

**Comment by BombayV** [comment]
Yeah. That was done in the update I told you about. Did you not update kek?
