### ISSUE TITLE
Got an error then trying to use command

### ISSUE THREAD

**Issue by OfficialKo1n** [BombayV/anims#35]
**Describe the bug**
Got an error then trying to use command

**To Reproduce**
1. use emote with command

**Screenshots**
**https://i.imgur.com/dXJZpWw.png**

**Comment by BombayV** [comment]
Are you using latest?

**Comment by OfficialKo1n** [comment]
yeah its latest.

**Comment by BombayV** [comment]
Weird. Well, I’ve been pushing changes without testing. I’ll test soon.

**Comment by Velkostatkar** [comment]
Hi its true some of the /e spiderman for  example do that error but /e dance works

**Comment by BombayV** [comment]
I'll test very soon.

**Comment by BombayV** [comment]
@OfficialKo1n @Velkostatkar Turns out it was an error with a wrong animation kek. Should have been fixed in the latest update.

https://github.com/BombayV/anims/commit/cea0efc49ba3b796ea6f53fa23754b07029819f6

**Comment by Velkostatkar** [comment]
> @OfficialKo1n @Velkostatkar Turns out it was an error with a wrong animation kek. Should have been fixed in the latest update.
> 
> [cea0efc](https://github.com/BombayV/anims/commit/cea0efc49ba3b796ea6f53fa23754b07029819f6)

Work perfect
jus one my player is unhappy becouse he cannot /e normal ,, on face impressions, becouse normal doesnot exist.

**Comment by BombayV** [comment]
I have no idea what that is. You can make a pull request for the expression.

**Comment by Velkostatkar** [comment]
Hehe never mind its like Default face
