### ISSUE TITLE
Client event for starting emote from another script

### ISSUE THREAD

**Issue by mhnl3** [BombayV/anims#4]
In other scripts we use dpemotes to call an emote. I wasn't sure how we can do this in your version without writing a new event/function to pass through the argument. 

Do you have this built in or can it be added? Example in a script we're using to sit down in chairs:

TriggerEvent('animations:client:EmoteCommandStart', {"sitchair"})

**Comment by BombayV** [comment]
This will be support by exports.
https://github.com/BombayV/anims/projects/1#card-75060440

**Comment by BombayV** [comment]
And this https://github.com/BombayV/anims/commit/d5128db66bd3081cab3aea6605e2ac519d2bb29c

It's not on production yet since I have to test it, but as soon as I finish it, I will push to production.

**Comment by BombayV** [comment]
`exports['anims']:PlayEmote('dance')`
