### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by emanueledenaro** [BombayV/anims#41]
![image](https://user-images.githubusercontent.com/79084923/156581932-080e8493-2c2a-4e49-9f47-274a2179abfe.png)
Something is missing, right?

**Comment by SeriumTW** [comment]
![image](https://user-images.githubusercontent.com/79084923/156582319-ea674bd5-fa6d-48fc-b1f4-83a404fe0242.png)
where is fetch.js???

**Comment by emanueledenaro** [comment]
![image](https://user-images.githubusercontent.com/79084923/156583582-5ebf1eed-54d3-4a12-bd33-f81884e2a381.png)

**Comment by BombayV** [comment]
I don't know why you would change the name of the resource. Either way, you can see #42
