### ISSUE TITLE
custom@ dict not work

### ISSUE THREAD

**Issue by diversao** [BombayV/anims#44]
**Describe the bug**
dict not load

**To Reproduce**
1. Go to 'github'
2. Download script
3. Start script

**Expected behavior**
load dict

**Additional context**
replace custom@ to custom@_anim_name_

**Comment by BombayV** [comment]
This seems like the dict doesn't exist.

**Comment by diversao** [comment]
for min so worked putting custom@anim_name 

**### only in anim addon**

ex:

{
        "type": "dances",
        "title": "Salsa",
        "subtitle": "/e salsa",
        "dances": {
            "dict": "custom@**salsa**",
            "anim": "salsa"
        },

**Comment by BombayV** [comment]
Feel free to make a pull request.
