### ISSUE TITLE
Make Able People when they sit can drink too

### ISSUE THREAD

**Issue by Gameadictive** [BombayV/anims#46]
Well title says it all.

People use sit in chairs and can drink too.-

**Comment by BombayV** [comment]
Sitting should be handled by other resource. This is used to play a single animation. Maybe something like [this](https://github.com/guicaulada/FiveM-Scripts/tree/master/vrpex/vrp_chairs) but made into a standalone resource.

**Comment by Gameadictive** [comment]
Just letting you know that dpemotes have this function. Thanks anyway.

**Comment by BombayV** [comment]
> Just letting you know that dpemotes have this function. Thanks anyway.

This animations panel is solely focused on animations, not anything else. Dpemotes has many plugins integrated into it which make it more than just animations. We are completely separated.

**Comment by Gameadictive** [comment]
Oh okay, thanks anyways.
