### ISSUE TITLE
key for opening the panel

### ISSUE THREAD

**Issue by ruivianapt** [BombayV/anims#47]
I'm trying to remove the key to open the animation panel and I set the keyActive on cfg to false but I still open the panel if I press F5.

I deleted the keyActive, keyLetter, keySuggestion lines, I deleted the character and I even deleted this line:
**if cfg.keyActive then
    RegisterKeyMapping(cfg.commandName, cfg.keySuggestion, 'keyboard', cfg.keyLetter)
end**   on nui.lua but still doesn't work. Eveytime I open the game when I press the key it opens the panel.

Anyone know how I can solve this issue?
Thanks

**Comment by VIRUXE** [comment]
It's still saved in your game settings.

**Comment by ruivianapt** [comment]
> It's still saved in your game settings.

So it can't be changed?

**Comment by BombayV** [comment]
Yes you can. Use `unbind keyboard <YOUR_KEY>`. This is because it's saved on your client but new users will not get affected by this.
