### ISSUE TITLE
SavedWalk don't work in QBCore

### ISSUE THREAD

**Issue by Juliroo** [BombayV/anims#48]
The system that saves the way you walk does not work in QBCore

**Comment by BombayV** [comment]
This was not an issue before. Do you mind telling me the error?

**Comment by Juliroo** [comment]
The PJ of the default skin is the one that adopts the way of walking, but when you load your skin the way of walking is removed

**Comment by BombayV** [comment]
Can't do much. You will have to implement a solution yourself so that the saved walk style function triggers again after the player spawn.
